const actionTypes = {
    GET_HOME: "GET_HOME",
    CHANGE_THEME: "CHANGE_THEME",
    GET_PLAYLIST: "GET_PLAYLIST",
    LOADING_PAGE: "LOADING_PAGE",

    // get music
    GET_INFO_SONG: "GET_INFO_SONG",
    LIST_MUSIC: "LIST_MUSIC",
    PLAY_MUSIC: "PLAY_MUSIC",
    TOGGLE_MUSIC: "TOGGLE_MUSIC",
    LOADING_MUSIC: "LOADING_MUSIC",
    WARNING_MUSIC: "WARNING_MUSIC",
    UPDATE_SONG: "UPDATE_SONG",
    NEXT_SONG: "NEXT_SONG",
    PREV_SONG: "PREV_SONG",
    STATUS_ALBUM: "STATUS_ALBUM",
    TOGGLE_SIDEBAR: "TOGGLE_SIDEBAR",
    ADD_MY_SONG: "ADD_MY_SONG",
    ADD_MY_PLAYLIST: "ADD_MY_PLAYLIST",
    REMOVE_MY_SONG: "REMOVE_MY_SONG",
    REMOVE_MY_PLAYLIST: "REMOVE_MY_PLAYLIST",
    REPEAT_MUSIC: "REPEAT_MUSIC",
};

export default actionTypes;
