const actionTypes = {
    GET_HOME: "GET_HOME",
    CHANGE_THEME: "CHANGE_THEME",
    UPDATE_HEADER: "UPDATE_HEADER",
    GET_PLAYLIST: "GET_PLAYLIST",
    LOADING_PAGE: "LOADING_PAGE",

    // get music
    GET_INFO_SONG: "GET_INFO_SONG",
    PLAY_MUSIC: "PLAY_MUSIC",
    TOGGLE_MUSIC: "TOGGLE_MUSIC",
    LOADING_MUSIC: "LOADING_MUSIC",
    WARNING_MUSIC: "WARNING_MUSIC",
};

export default actionTypes;
